### ISSUE TITLE
"No lines found"

### ISSUE THREAD

**Issue by ExTechOp** [otsaloma/helsinki-transit-live#4] opened 2017-10-30 08:37 UTC
On a JollaC (Sailfish OS 2.1.2.3 Kiiminkijoki), using the version 1.4.210 line selector will give you a "No lines found" message whatever values you try. I was able to initially (several months ago) make a selection of lines, and those seem to still be there and are shown by the program, but I cannot add new lines or make changes because of this. Has the API at the server end changed?

**Comment by otsaloma** [comment] 2017-10-30 22:15
I just tried and it works for me. I do remember seeing the same issue before, but I figured it was just a temporary problem with the API. The list of the lines is from the below URL, it should up to date.

http://api.digitransit.fi/routing/v1/routers/hsl/index/routes

**Comment by ExTechOp** [comment] 2017-10-31 06:08
Retried it, "No lines found" displayed immediately when I go into the "Line or vehicle type" selection, even before entering any values. What would you recommend I do to help debug this issue?

![20171030](https://user-images.githubusercontent.com/12744438/32209709-49ec4016-be12-11e7-8b3b-2a8c4b9c91ab.jpg)

**Comment by otsaloma** [comment] 2017-10-31 22:46
What I tried earlier was the latest development version. Now that I tried the latest release, I can reproduce the problem. There has indeed been a minor change on the server side, but it's fixed by a [commit](https://github.com/otsaloma/helsinki-transit-live/commit/07201f431ee2e037897a5fba7f48ea381a9a4fbb) I made before the problem appeared. So, I just need to make a new release, I'll try to do that in the next couple days.

**Comment by ExTechOp** [comment] 2017-11-01 10:32
Excellent, looking forward to this release!

**Comment by otsaloma** [comment] 2017-11-01 20:13
Fixed in version 1.5.

**Closed as completed by otsaloma** 2017-11-01 20:13 UTC

**Comment by ExTechOp** [comment] 2017-11-02 16:12
Thank you, this seems to have fixed the issue!
